GRAPH_SCHEMA = (
    "Nodes:\n"
    "- ChuongTrinhDaoTao(ma_chuong_trinh, khoa, he, ngon_ngu, tong_tin_chi, thoi_gian_dao_tao, thang_diem): Thực thể trung tâm quản lý chương trình đào tạo.\n"
    "- DoiTuongTuyenSinh(noi_dung): Đối tượng tuyển sinh (VD: Tốt nghiệp THPT hoặc tương đương).\n"
    "- DieuKienTotNghiep(noi_dung): Điều kiện tốt nghiệp (VD: Hoàn thành 120 TC, có điểm trung bình tích lũy tối thiểu 2.0).\n"
    "- HocPhan(ma_hoc_phan, ten_hoc_phan, so_tin_chi, so_tiet_ly_thuyet, so_tiet_thuc_hanh, tom_tat, bat_buoc): Chi tiết về môn học.\n"
    "- KhoiKienThuc(ma_khoi, ten_khoi, tong_tin_chi, tin_chi_bat_buoc, tin_chi_tu_chon): Các khối như GD đại cương, Cơ sở ngành.\n"
    "- ChuanDauRa(ma_chuan, noi_dung, nhom, loai): Các chuẩn PLO phân theo Kiến thức/Kỹ năng/Mức độ tự chủ và trách nhiệm cá nhân. (VD: nhom: "Kỹ năng cứng", loai: "Kỹ năng")\n"
    "- VanBanPhapLy(so, ten, loai, ngay_ban_hanh, co_quan_ban_hanh, noi_dung_goc): Quyết định ban hành hoặc văn bản căn cứ.\n"
    "- Nganh(ma_nganh, ten_nganh_vi, ten_nganh_en): Thông tin ngành đào tạo.\n"
    "- Khoa(ma_khoa, ten_khoa): Khoa/Trường.\n"
    "- BoMon(ma_bo_mon, ten_bo_mon): Bộ môn.\n"
    "- TrinhDo(ma_trinh_do, ten_trinh_do): Cấp bậc đào tạo (Đại học/Cao đẳng/Thạc sĩ/Tiến sĩ).\n"
    "- LoaiVanBang(ma_loai, loai_van_bang): Danh hiệu văn bằng (Kỹ sư/Cử nhân/Thạc sĩ/Tiến sĩ).\n"
    "- HinhThucDaoTao(ma_hinh_thuc, ten_hinh_thuc): Hình thức đào tạo (Chính quy/Vừa làm vừa học/Đào tạo từ xa).\n"
    "- PhuongThucDaoTao(ma_phuong_thuc, ten_phuong_thuc): Phương thức đào tạo (Trực tiếp/Trực tuyến).\n"
    "- MucTieuDaoTao(loai, noi_dung): Mục tiêu PEOs chung hoặc cụ thể.\n"
    "- ViTriViecLam(noi_dung): Cơ hội nghề nghiệp sau tốt nghiệp.\n"
    "- ChuanThamKhao(noi_dung, link, noi_dung_goc): Tài liệu hoặc chuẩn tham chiếu quốc tế.\n"
    "- DanhGiaKiemDinh(noi_dung): Thông tin về đánh giá và kiểm định chất lượng chương trình đào tạo.\n"
    "- KhaNangHocTap(noi_dung): Khả năng học tập sau tốt nghiệp.\n"
    "- NhomHocPhanTuChon(ten_nhom): Nhóm nhỏ môn học trong yêu cầu tự chọn. (VD: AV, PV)\n"
    "- YeuCauTuChon(noi_dung_yeu_cau, so_tin_chi_yeu_cau): Ràng buộc nhóm học phần tự chọn và số tín chỉ tự chọn (VD:, N1 hoặc N2, Chọn 10 TC).\n\n"

    "Edges:\n"
    "- (:ChuongTrinhDaoTao)-[:BAN_HANH_THEO]->(:VanBanPhapLy)\n"
    "- (:ChuongTrinhDaoTao)-[:DAO_TAO]->(:TrinhDo)\n"
    "- (:ChuongTrinhDaoTao)-[:THUOC_VE]->(:Nganh)\n"
    "- (:Nganh)-[:THUOC_VE]->(:Khoa|:BoMon)\n"
    "- (:BoMon)-[:THUOC_VE]->(:Khoa)\n"
    "- (:ChuongTrinhDaoTao)-[:CAP]->(:LoaiVanBang)\n"
    "- (:ChuongTrinhDaoTao)-[:CO]->(:HinhThucDaoTao)\n"
    "- (:ChuongTrinhDaoTao)-[:CO]->(:PhuongThucDaoTao)\n"
    "- (:ChuongTrinhDaoTao)-[:CO]->(:DoiTuongTuyenSinh)\n"
    "- (:ChuongTrinhDaoTao)-[:CO]->(:MucTieuDaoTao)\n"
    "- (:ChuongTrinhDaoTao)-[:CO]->(:DanhGiaKiemDinh)\n"
    "- (:ChuongTrinhDaoTao)-[:CO]->(:ViTriViecLam)\n"
    "- (:ChuongTrinhDaoTao)-[:THAM_KHAO]->(:ChuanThamKhao)\n"
    "- (:ChuongTrinhDaoTao)-[:DAT_DUOC]->(:KhaNangHocTap)\n"
    "- (:ChuongTrinhDaoTao)-[:CO]->(:ChuanDauRa)\n"
    "- (:ChuongTrinhDaoTao)-[:YEU_CAU]->(:DieuKienTotNghiep)\n"
    "- (:ChuongTrinhDaoTao)-[:GOM]->(:KhoiKienThuc)\n"
    "- (:ChuongTrinhDaoTao)-[:GOM]->(:HocPhan)\n"
    "- (:KhoiKienThuc)-[:CO]->(:YeuCauTuChon)\n"
    "- (:KhoiKienThuc)-[:GOM]->(:HocPhan)\n"
    "- (:YeuCauTuChon)-[:DOI_VOI]->(:NhomHocPhanTuChon)\n"
    "- (:NhomHocPhanTuChon)-[:GOM]->(:HocPhan)\n"
    "- (:HocPhan)-[:YEU_CAU_TIEN_QUYET]->(:HocPhan)\n"
    "- (:HocPhan)-[:CO_THE_SONG_HANH]->(:HocPhan)\n"
) 